# Generated by Django 3.2.14 on 2022-07-21 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0003_alter_blog_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.agent')),
            ],
        ),
    ]
