# Generated by Django 3.2.14 on 2022-10-12 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0005_agentaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='age',
            field=models.IntegerField(verbose_name='age'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='img'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='name',
            field=models.CharField(max_length=50, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='skype',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='skype'),
        ),
        migrations.AlterField(
            model_name='amenity',
            name='name',
            field=models.CharField(choices=[('Balcony', 'Balcony'), ('Cable TV', 'Cable TV'), ('Internet', 'Internet'), ('Tennis Courts', 'Tennis Courts'), ('Parking', 'Parking')], max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='author',
            field=models.CharField(max_length=50, verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(max_length=50, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.TextField(verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='img',
            field=models.ImageField(upload_to='images', verbose_name='img'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=50, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='houses.blog', verbose_name='blog'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='img',
            field=models.ImageField(upload_to='images', verbose_name='img'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user_name',
            field=models.CharField(max_length=50, verbose_name='user_name'),
        ),
        migrations.AlterField(
            model_name='house',
            name='address',
            field=models.CharField(max_length=50, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='house',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.agent', verbose_name='agent'),
        ),
        migrations.AlterField(
            model_name='house',
            name='amenities',
            field=models.ManyToManyField(to='houses.Amenity', verbose_name='amenities'),
        ),
        migrations.AlterField(
            model_name='house',
            name='area',
            field=models.IntegerField(verbose_name='area'),
        ),
        migrations.AlterField(
            model_name='house',
            name='bathrooms',
            field=models.IntegerField(verbose_name='bathrooms'),
        ),
        migrations.AlterField(
            model_name='house',
            name='beds',
            field=models.IntegerField(verbose_name='beds'),
        ),
        migrations.AlterField(
            model_name='house',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='house',
            name='garages',
            field=models.IntegerField(verbose_name='garages'),
        ),
        migrations.AlterField(
            model_name='house',
            name='img',
            field=models.ImageField(upload_to='images', verbose_name='img'),
        ),
        migrations.AlterField(
            model_name='house',
            name='location',
            field=models.CharField(max_length=50, verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='house',
            name='price',
            field=models.IntegerField(verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='house',
            name='status',
            field=models.CharField(choices=[('sale', 'sale'), ('rent', 'rent')], max_length=100, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='message',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='houses.agent', verbose_name='agent'),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='message',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='message',
            name='user_name',
            field=models.CharField(max_length=50, verbose_name='user_name'),
        ),
    ]
