# Generated by Django 3.2.14 on 2022-10-13 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0008_alter_house_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
