# Generated by Django 3.2.14 on 2022-10-14 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0010_alter_message_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='blog',
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
