# Generated by Django 3.2.14 on 2022-10-14 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0012_message_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='message',
            name='agent',
        ),
        migrations.DeleteModel(
            name='AgentAccount',
        ),
    ]
