# Generated by Django 3.2.14 on 2022-10-16 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0016_inquiry_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
