# Generated by Django 3.2.14 on 2022-10-19 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0017_inquiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
