# Generated by Django 3.2.14 on 2022-10-20 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0020_auto_20221019_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='houses.company'),
        ),
        migrations.AddField(
            model_name='house',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='houses.project'),
        ),
    ]
